deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: animethemes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animethemes
  template:
    metadata:
      labels:
        app: animethemes
    spec:
      containers:
      - name: animethemes
        image: animethemes-shuffler:latest
        ports:
        - containerPort: 80
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "animethemes"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql